http:
  port: "3000"

postgres:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "gomservice"
  sslmode: "disable"

jwt:
  secret: "supersecretkey"
  exp_minutes: 30